//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.29 at 11:19:48 PM EET 
//


package com.karniyarik.recognizer.xml.item;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for itemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alternatenames" type="{http://www.karniyarik.com/schema}alternatenamesType"/>
 *         &lt;element name="references" type="{http://www.karniyarik.com/schema}referencesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = {
    "alternatenames",
    "references"
})
public class ItemType {

    @XmlElement(required = true)
    protected AlternatenamesType alternatenames;
    @XmlElement(required = true)
    protected ReferencesType references;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the alternatenames property.
     * 
     * @return
     *     possible object is
     *     {@link AlternatenamesType }
     *     
     */
    public AlternatenamesType getAlternatenames() {
        return alternatenames;
    }

    /**
     * Sets the value of the alternatenames property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternatenamesType }
     *     
     */
    public void setAlternatenames(AlternatenamesType value) {
        this.alternatenames = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesType }
     *     
     */
    public ReferencesType getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesType }
     *     
     */
    public void setReferences(ReferencesType value) {
        this.references = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
