mvn install:install-file  -DgroupId=zemberek  -DartifactId=zemberek  -Dversion=2.0 -Dpackaging=jar  -Dfile=zemberek-tum-2.0.jar -DgeneratePom=true
mvn install:install-file  -DgroupId=zemberek  -DartifactId=zemberek-core  -Dversion=2.1.1 -Dpackaging=jar  -Dfile=zemberek-cekirdek-2.1.1.jar -DgeneratePom=true
mvn install:install-file  -DgroupId=zemberek  -DartifactId=zemberek-tr  -Dversion=2.1.1 -Dpackaging=jar  -Dfile=zemberek-tr-2.1.1.jar -DgeneratePom=true
mvn install:install-file  -DgroupId=zemberek  -DartifactId=zemberek-core  -Dversion=2.1.99 -Dpackaging=jar  -Dfile=zemberek-cekirdek-2.1.99.jar -DgeneratePom=true
mvn install:install-file  -DgroupId=zemberek  -DartifactId=zemberek-tr  -Dversion=2.1.99 -Dpackaging=jar  -Dfile=zemberek-tr-2.1.99.jar -DgeneratePom=true
mvn install:install-file  -DgroupId=simplecaptcha  -DartifactId=simplecaptcha  -Dversion=1.1.1 -Dpackaging=jar  -Dfile=simplecaptcha-1.1.1.jar -DgeneratePom=true
mvn install:install-file  -DgroupId=org.tuckey -DartifactId=urlrewritefilter -Dversion=3.2.0 -Dpackaging=jar -Dfile=urlrewritefilter-3.2.0.jar -Dsources=urlrewritefilter-3.2.0-sources.jar
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon -Dfile=saxon9.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-dom4j -Dfile=saxon9-dom4j.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-dom -Dfile=saxon9-dom.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-jdom -Dfile=saxon9-jdom.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-s9api -Dfile=saxon9-s9api.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxonsa -Dfile=saxon9sa.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxonsa-jaxp -Dfile=saxon9sa-jaxp.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxonsa-qc -Dfile=saxon9sa-qc.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-sql -Dfile=saxon9-sql.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-xom -Dfile=saxon9-xom.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-xpath -Dfile=saxon9-xpath.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=net.sf.saxon -DartifactId=saxon-xqj -Dfile=saxon9-xqj.jar -Dversion=9.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=org.htmlcleaner -DartifactId=htmlcleaner -Dfile=htmlcleaner2_1.jar -Dversion=2.1 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=org.opensymphony.quartz -DartifactId=quartz -Dfile=quartz-1.6.5.jar -Dversion=1.6.5 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=weka -DartifactId=weka -Dfile=weka.jar -Dversion=3.6 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.aliasi -DartifactId=lingpipe -Dfile=lingpipe-3.8.2.jar -Dversion=3.8.2 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=org.dyno.visual.swing -DartifactId=layoutext -Dfile=grouplayout.jar -Dversion=1.x -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=cz.mallat -DartifactId=uasparser -Dfile=UASparser.jar -Dversion=0.1-SNAPSHOT -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=cn.heapstack -DartifactId=rss -Dfile=rss_generator_v0.1.jar -Dversion=0.1 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=org.jgroups -DartifactId=jgroups -Dfile=jgroups-2.10.0.GA.jar -Dversion=2.10 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=google-collect -Dfile=google-collect-1.0-rc1.jar -Dversion=1.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=jsr305 -Dfile=jsr305.jar -Dversion=1.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=gdata-core -Dfile=gdata-core-1.0.jar -Dversion=1.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=gdata-client-meta -Dfile=gdata-client-meta-1.0.jar -Dversion=1.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=gdata-client -Dfile=gdata-client-1.0.jar -Dversion=1.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=gdata-analytics -Dfile=gdata-analytics-2.1.jar -Dversion=2.1 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=gdata-analytics-meta -Dfile=gdata-analytics-meta-2.1.jar -Dversion=2.1 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=gdata-webmastertools -Dfile=gdata-webmastertools-2.0.jar -Dversion=2.0 -Dpackaging=jar  -DgeneratePom=true
mvn install:install-file  -DgroupId=com.google -DartifactId=gdata-webmastertools-meta -Dfile=gdata-webmastertools-meta-2.0.jar -Dversion=2.0 -Dpackaging=jar  -DgeneratePom=true